shell.execute("label", "set", "Setuping 1/3, Downloading TunnelV2")
shell.execute("pastebin", "get", "3yHGPqcy", "tunnelV2")
shell.execute("label", "set", "Setuping 2/3, init Startup")
shell.execute("pastebin", "get", "zhuZargD", "startup.lua")
shell.execute("label", "set", "Setuping 3/3, Add Fuel")
shell.execute("refuel", "64")
shell.execute("label", "set", "tunneler")
